"""
Scan content/lessons/*.md and emit services/lessons.generated.ts so the app
can ship lesson content bundled in JS (no asset loading, no Supabase round
trip). Re-run after capturing new lessons with the bookmarklet.

Usage:
    python scripts/build-lessons-index.py
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LESSONS_DIR = ROOT / 'content' / 'lessons'
OUT = ROOT / 'services' / 'lessons.generated.ts'

FRONTMATTER_RE = re.compile(r'^---\n(.*?)\n---\n?(.*)$', re.DOTALL)
QUOTED_VALUE_RE = re.compile(r'^"((?:[^"\\]|\\.)*)"$')


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}, text
    front_raw, body = m.group(1), m.group(2)
    meta: dict[str, str] = {}
    for line in front_raw.splitlines():
        if ':' not in line:
            continue
        key, _, value = line.partition(':')
        key = key.strip()
        value = value.strip()
        qm = QUOTED_VALUE_RE.match(value)
        if qm:
            value = qm.group(1).encode().decode('unicode_escape')
        meta[key] = value
    return meta, body.lstrip('\n')


def slug_from_filename(name: str) -> str:
    # lessons-days.md -> days
    base = name.removesuffix('.md')
    return base.removeprefix('lessons-')


def main() -> int:
    if not LESSONS_DIR.exists():
        print(f'no lessons dir at {LESSONS_DIR}')
        return 1

    entries: list[dict[str, str]] = []
    for path in sorted(LESSONS_DIR.glob('lessons-*.md')):
        text = path.read_text(encoding='utf-8')
        meta, body = parse_frontmatter(text)
        entries.append({
            'slug': slug_from_filename(path.name),
            'title': meta.get('title', path.stem),
            'sourceUrl': meta.get('source_url', ''),
            'fetchedAt': meta.get('fetched_at', ''),
            'body': body,
        })

    lines: list[str] = []
    lines.append('// Generated by scripts/build-lessons-index.py — do not edit by hand.')
    lines.append('// Re-run after capturing new lessons with the bookmarklet.')
    lines.append('')
    lines.append('export type LessonRecord = {')
    lines.append('  slug: string;')
    lines.append('  title: string;')
    lines.append('  sourceUrl: string;')
    lines.append('  fetchedAt: string;')
    lines.append('  body: string;')
    lines.append('};')
    lines.append('')
    lines.append('export const LESSONS: Record<string, LessonRecord> = {')
    for e in entries:
        lines.append(f'  {json.dumps(e["slug"])}: {{')
        lines.append(f'    slug: {json.dumps(e["slug"])},')
        lines.append(f'    title: {json.dumps(e["title"])},')
        lines.append(f'    sourceUrl: {json.dumps(e["sourceUrl"])},')
        lines.append(f'    fetchedAt: {json.dumps(e["fetchedAt"])},')
        lines.append(f'    body: {json.dumps(e["body"])},')
        lines.append('  },')
    lines.append('};')
    lines.append('')
    lines.append('export const LESSON_SLUGS: readonly string[] = [')
    for e in entries:
        lines.append(f'  {json.dumps(e["slug"])},')
    lines.append('];')
    lines.append('')

    OUT.write_text('\n'.join(lines), encoding='utf-8')
    print(f'wrote {OUT.relative_to(ROOT)} ({len(entries)} lessons)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
