"""
Read an Anki .apkg conjugation deck and emit a Postgres SQL seed file ready
to paste into the Supabase SQL editor.

Usage:
    python scripts/import_anki_conjugation.py \\
        --apkg "content/Ultimate_Spanish_Conjugation_Lisardos_KOFI_Method.apkg" \\
        --out  "supabase/seeds/02-conjugation-cards.sql"

Output is a single INSERT into public.conjugation_cards. Re-running the script
is safe: an `on conflict (sequence) do nothing` clause covers re-imports.

Skips Anki's five orientation cards. Cloze syntax {{c1::answer::hint}} is
preserved verbatim so the app renderer can split front/back. HTML markup is
stripped (br -> ' / ', everything else removed). The verb is extracted from
the tag list using a stop-list of known meta tokens.
"""

from __future__ import annotations
import argparse
import html
import json
import os
import re
import sqlite3
import sys
import tempfile
import zipfile
from typing import Iterable

# Meta tags that are never the verb. Anki tags are space-separated; the verb
# is the one short, simple, non-meta token in the list.
META_TAGS = {
    'orientation',
    # tenses and moods
    'presente', 'imperfecto', 'preterito', 'pretérito', 'futuro',
    'condicional', 'subjuntivo', 'imperativo', 'perfecto',
    'pluscuamperfecto', 'antepreterito', 'anteperfecto', 'antefuturo',
    'pluscuampérfecto', 'antepretérito',
    # non-finite
    'participio', 'gerundio', 'infinitivo',
    # persons
    'yo', 'tu', 'tú', 'el', 'él', 'ella', 'ello', 'usted',
    'nosotros', 'nosotras', 'vosotros', 'vosotras', 'ellos', 'ellas', 'ustedes',
    # regularity / shape markers (no underscore in some)
}

HTML_BR = re.compile(r'<br\s*/?>', re.IGNORECASE)
HTML_TAG = re.compile(r'<[^>]+>')
WHITESPACE = re.compile(r'[ \t]+')
MULTI_NEWLINE = re.compile(r'\n{2,}')


def strip_html(s: str) -> str:
    if not s:
        return ''
    s = HTML_BR.sub(' / ', s)
    s = HTML_TAG.sub('', s)
    s = html.unescape(s)
    s = s.replace('\r', '')
    s = WHITESPACE.sub(' ', s)
    s = MULTI_NEWLINE.sub('\n', s)
    return s.strip()


def clean_prompt(prompt: str) -> str:
    """
    Preserve the cloze tokens `{{c\\d+::...}}` verbatim; strip surrounding HTML.
    """
    return strip_html(prompt)


def extract_verb(tags_str: str) -> str | None:
    candidates: list[str] = []
    for t in tags_str.strip().split():
        if '_' in t:
            continue
        if t.lower() in META_TAGS:
            continue
        candidates.append(t)
    # The infinitive tends to be the last simple token in the tag list.
    return candidates[-1] if candidates else None


def sql_escape(s: str | None) -> str:
    if s is None:
        return 'null'
    # Single-quote escape per Postgres standard.
    return "'" + s.replace("'", "''") + "'"


def sql_array(items: Iterable[str]) -> str:
    # Postgres text[] literal.
    escaped = ['"' + i.replace('\\', '\\\\').replace('"', '\\"') + '"' for i in items]
    return "'{" + ",".join(escaped) + "}'"


def iter_notes(apkg_path: str):
    with tempfile.TemporaryDirectory() as tmp:
        with zipfile.ZipFile(apkg_path) as z:
            z.extractall(tmp)
        # Prefer the newer collection format if present.
        for name in ('collection.anki21', 'collection.anki2'):
            db_path = os.path.join(tmp, name)
            if os.path.exists(db_path):
                break
        else:
            raise SystemExit(f'No Anki collection DB found inside {apkg_path}')
        conn = sqlite3.connect(db_path)
        try:
            rows = conn.execute(
                "SELECT id, flds, tags FROM notes WHERE tags NOT LIKE '%orientation%' ORDER BY id ASC"
            ).fetchall()
            for nid, flds, tags in rows:
                fields = flds.split('\x1f')
                # Model has: UUID, Prompt, Similar, Notes
                prompt = fields[1] if len(fields) > 1 else ''
                notes  = fields[3] if len(fields) > 3 else ''
                yield {
                    'note_id': nid,
                    'prompt': clean_prompt(prompt),
                    'notes': strip_html(notes) or None,
                    'tags': tags.strip().split(),
                    'verb': extract_verb(tags),
                }
        finally:
            conn.close()


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument('--apkg', required=True)
    p.add_argument('--out', required=True)
    args = p.parse_args()

    rows = list(iter_notes(args.apkg))
    if not rows:
        print('No usable cards found.', file=sys.stderr)
        return 1

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, 'w', encoding='utf-8', newline='\n') as f:
        f.write('-- Generated by scripts/import_anki_conjugation.py.\n')
        f.write('-- Do not edit by hand; re-run the script to regenerate.\n')
        f.write(f'-- Source apkg: {os.path.basename(args.apkg)}\n')
        f.write(f'-- Cards: {len(rows)}\n\n')
        f.write('insert into public.conjugation_cards (sequence, prompt, notes, tags, verb) values\n')
        for i, r in enumerate(rows):
            sep = ',' if i < len(rows) - 1 else ''
            f.write(
                '  ('
                f'{i + 1}, '
                f'{sql_escape(r["prompt"])}, '
                f'{sql_escape(r["notes"])}, '
                f'{sql_array(r["tags"])}, '
                f'{sql_escape(r["verb"])}'
                f'){sep}\n'
            )
        f.write('on conflict (sequence) do nothing;\n')

    print(f'Wrote {len(rows)} cards to {args.out}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
